---
title: "HGP analysis"
author: 
- name: Rick Farouni, 
  affiliation:
  - &cruk Department of Human Genetics, McGill University,  Montreal, Canada
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_notebook:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

# Preparations

```{r setup}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file(), fig.width=16)
options(scipen=999)
```

```{r}
library(Matrix)
#library(irlba)
#library(threejs)
library(tidyverse)
library(lfa)
library(furrr)
library(broom)
options(future.globals.maxSize= 10000000000)
plan(multicore)
```

# Download metadata

Download bas files for all the samples 

```{bash message=FALSE}
for id in `cat ids.txt`
  do
  wget ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/${id}/alignment/${id}.mapped.*.bam.bas -P ./data/bas
done
wait
```

## Read bas files

```{r read_bas}
read_basfiles <- function(bas_filepath) {
  
  bas_file <- read_tsv(bas_filepath,
                  col_types = cols_only('sample' = 'c', 
                                        'platform' = 'c',        
                                       'average_quality_of_mapped_bases' = col_guess())) 
  return( bas_file)
}
```

### Preprocess table

```{r}
bas_files <- list.files(path = ".",
                        pattern="*bam.bas")

bas_dt <- 
  map_dfr(bas_files,read_basfiles ) %>%
  rename(avg_qual="average_quality_of_mapped_bases")
bas_dt
```


```{r}
bas_dt <-
  bas_dt %>%
  group_by(sample) %>%
  mutate(id=1:n()) %>%
  select(-platform)%>%
  spread(id,avg_qual)
bas_dt
```
```{r}
n_not_na <- function(x) {
 sum(!is.na(x))
}
```


```{r}
 bas_dt <- 
  bas_dt %>%
  ungroup()%>% 
    mutate( avg_qual_sd =pmap_dbl(select(., -sample), lift_vd(sd,na.rm =TRUE )),
           avg_qual_mean = rowMeans(select(., -sample),na.rm =TRUE),
           avg_qual_n= pmap_dbl(select(., -sample), lift_vd(n_not_na)),
           avg_qual_min= pmap_dbl(select(., -sample), lift_vd(min, na.rm =TRUE)),
           avg_qual_max= pmap_dbl(select(., -sample), lift_vd(max, na.rm =TRUE))) %>%
  select (sample, avg_qual_n, avg_qual_min,avg_qual_max,avg_qual_mean,avg_qual_sd, everything() ) 
```



```{r}
ped <- 
  read_tsv(url("ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/working/20130606_sample_info/20130606_g1k.ped"))%>% 
  rename(sample="Individual ID")
ped 
```


```{r}
bas_dt <- inner_join( ped  %>% 
                       select(sample, Population),
                       bas_dt,
                     by="sample")
bas_dt
```


```{r}
bas_filepath <- "./data/metadata/average_quality_dt.txt"
write_tsv(bas_dt, bas_filepath)
```

Plot 
 

```{r fig.width=20}
ggplot(bas_dt,
       aes(x=avg_qual_min,
           y=avg_qual_max, 
           colour=avg_qual_n )) +
  geom_point(size=2)
 
```


```{r fig.width=20}
ggplot(bas_dt,
       aes(x=avg_qual_mean,
           y=avg_qual_sd, 
           colour=avg_qual_n )) +
  geom_point(size=2)
 
```


# Logistic factor analysis

```{r}
bas_dt <- read_tsv(bas_filepath)
avg_qual_mean <- bas_dt$avg_qual_mean
```

```{r}

to_datalist <- function(i, data_genotype, data_iaf){
  
    data <- tibble(genotype=data_genotype[i,],
               iaf=data_iaf[i,])
               
     return(data)       
}

  
get_af_data <- function(data, d=4){
  

  # compute the first d factors including the intercept
  
  message("running lfa")

  LF <- lfa(data, d)
  # compute the individual-specific allele frequencies
  
  message("running  af")

  data_iaf <- af(data, LF)
  loci <- c(1:dim(data)[1])
  names(loci) <- loci
  
  message("to datalist")

  data_list <- future_map(loci, 
                 to_datalist,
                 data_genotype=data,
                 data_iaf=data_iaf) 
  
  data_list <- 
  enframe(data_list,
          name = "locus", 
          value = "dataset")
  
  return(data_list)
  
}

get_predicted_mean <- function(model_fit) {
 predicted <- 
   augment(model_fit, type.predict = "response") %>%
   select("genotype","offset.iaf.",".fitted") %>%
   rename(iaf="offset.iaf.", mu=".fitted" )
  return(predicted)
}

get_stats <- function(model_fit){
  stats_dt <- 
    tidy(model_fit)  %>%
    filter(term=="avg_qual_mean") %>%
    select(estimate, p.value) %>%
    mutate(deviance= anova(model_fit)["Deviance"][[1]][2])
  return(stats_dt)
}



fit_model <- function(dataset){
  
   fit <- glm(genotype ~ avg_qual_mean + offset(iaf),
                           family ="binomial",
                           data=dataset)
   
   stats <- get_stats(fit)
   predicted <- get_predicted_mean(fit)
   
   return(list(stats, predicted))
}

get_plot <- function(data){
  
 p <- ggplot(bind_cols(data, 
                   bas_dt %>% 
                     select(Population,
                            avg_qual_mean))) +
    geom_point(aes(avg_qual_mean, 
                   genotype),
               size=.5,
               alpha= 0.4) +
    geom_line(aes(avg_qual_mean,
                  iaf, 
                  colour="af"),
              linetype="dashed") +
    geom_line(aes(avg_qual_mean,
                  mu,
                  colour="mu")) +
      theme_bw() +
    facet_wrap(~Population)
  
  return(p)
}
```


```{r}
run_workflow <- function(loci){

  data <- read.bed("./data/plink/ALL_Pops")
  
  message("plink data loaded")
  
  data_list <- get_af_data(data) 
  
  rm(data)
  gc()
  
  message("fitting model")
  
  data_list <- 
    data_list %>%
  #slice(1:10) %>%
  transmute(
    locus=locus,
    fit1 = future_map(dataset, fit_model))  %>%
  transmute(
    locus=locus,
    stats = future_map(fit1, c(1)),
    predicted =future_map(fit1, c(2))) %>%
    unnest(stats) %>%
    arrange(-deviance) 
  
  return(data_list)
  
}


```


```{r}
data_list <- run_workflow ()
data_list
```

```{r save_data}
saveRDS(data_list, "./data/preprocessed/data_fit.rds")
```


```{r}
n <-20
target_loci <- 
  data_list %>% 
  slice(1:n) %>% 
  pull(locus)
target_loci 
```

```{r}
data_list_subset <- 
  data_list %>%
   filter(locus %in% target_loci ) %>%
    mutate(plotted= future_map(predicted, get_plot)) 
data_list_subset
```



```{r}
data_list_subset %>%
  pull(plotted)
```




```{r}
sessionInfo()
```








