---
title: "HGP analysis: fit model"
author: 
- name: Rick Farouni, 
  affiliation:
  - &cruk Department of Human Genetics, McGill University,  Montreal, Canada
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_notebook:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

# Preparations

```{r setup}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file(), fig.width=16)
options(scipen=999)
```

```{r}
library(tidyverse)
library(lfa)
library(furrr)
library(tictoc)
options(future.globals.maxSize= 1000000000000)
plan(multicore)
```

```{r}
gc()
```

```{r}
gcinfo(TRUE) 
```


#  Fit model


```{r}
to_datalist <- function(i){
  
    data <- tibble(genotype=data_genotype[i,],
               iaf=data_iaf[i,])
               
     return(data)       
}

```

```{r}
data_genotype <- read.bed("./data/plink/ALL_Pops")
message("plink data loaded")


data_iaf <- readRDS("./data/preprocessed/iaf.rds")

loci <- c(1:dim(data_genotype)[1])
names(loci) <- loci

message("to datalist")

tic()
data_list <- future_map(loci, 
         to_datalist) 

toc()

data_list <- 
enframe(data_list,
  name = "locus", 
  value = "dataset")

saveRDS(data_list, "./data/preprocessed/data_list.rds")
```


```{r}
sessionInfo()
```








