---
title: "HGP analysis: fit model"
author: 
- name: Rick Farouni, 
  affiliation:
  - &cruk Department of Human Genetics, McGill University,  Montreal, Canada
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_notebook:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float: 
      collapsed: false
      smooth_scroll: false
---


# Preparations

```{r setup}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file(), fig.width=16)
options(scipen=999)
```

```{r}
library(tidyverse)
library(lfa)
library(glm2)
library(furrr)
library(broom)
library(tictoc)
options(future.globals.maxSize= 1000000000000)
plan(multicore)
```

```{r}
gc()
```


```{r}
data_list <- readRDS("./data/preprocessed/data_list.rds")
```

```{r}
gc()
```


```{r}

get_predicted_mean <- function(dataset, fit1, fit2) {
  dataset <-
    dataset %>%
    mutate(p_0 = predict(fit1, type = c("response")),
           p_1 = predict(fit2, type = c("response")))
  
  return(dataset)
}

get_stats <- function(dataset, fit2) {
  
  stats_dt <-
    tidy(fit2)  %>%
    filter(term == "avg_qual_mean") %>%
    select(estimate, p.value) %>%
    mutate(qual_logp = -log10(p.value),
           nobs = df.residual(fit2) + 2L)
  
  deviance_dt <-
    dataset %>%
    summarize(
      dev0 = -2 * sum(genotype * log(p_0) +
                        (1 - genotype) * log(1 - p_0),
                      na.rm = TRUE),
      dev1 = -2 * sum(genotype * log(p_1) +
                        (1 - genotype) * log(1 - p_1),
                      na.rm = TRUE),
      devdiff = dev0 - dev1,
      dev_logp = -log10(pchisq(devdiff,
                               1,
                               lower.tail = FALSE))
    )
  
  stats_dt  <- bind_cols(stats_dt,
                         deviance_dt)
  
  return(stats_dt)
}



fit_model <- function(dataset) {
  dataset <-
    dataset %>%
    mutate(genotype = as.integer(genotype > 0))
  
  fit1 <- glm2(
    genotype ~  offset(iaf),
    family = "binomial",
    data = dataset,
    na.action = "na.exclude"
  )
  
  fit2 <- glm2(
    genotype ~ avg_qual_mean + offset(iaf),
    family = "binomial",
    data = dataset,
    na.action = "na.exclude"
  )
  
  
  
  dataset <- get_predicted_mean(dataset, fit1, fit2)
  
  stats <- get_stats(dataset, fit2)
  
  
  
  return(list(stats=stats, datatset=dataset))
}


```


```{r}
bas_filepath <- "./data/metadata/average_quality_dt.txt"
bas_dt <- read_tsv(bas_filepath)
avg_qual_mean <- bas_dt$avg_qual_mean
```
```{r}
head(avg_qual_mean)
```



```{r}
fit_subset <- function(sub_index) {
  
  message("fitting model")
  tic()
  data_list_sub <- 
    data_list %>%
    slice(sub_index) %>%
    transmute(
      locus=locus,
      fit1 = future_map(dataset, fit_model))  %>%
    unnest(fit1) %>%
    mutate(l= rep(c("stat","data"), n()/2))%>%
    spread(l, fit1)%>%
    unnest(stat)
  toc()
  return(data_list_sub)
  
}
```


```{r}
S <-30
m <- 76871
subset <- vector("list", length = S)
for(i in 1:S){
  strt <- m*(i-1) +1
  stp <- m*i
  sub_range <- c(strt:stp)
  print(i)
  subset <- fit_subset(sub_range) 
  saveRDS(subset, file.path("./data/preprocessed/subsets", paste0("fits_subset_", i, ".rds")))
}
```


```{r}
gc()
```



```{r}
sessionInfo()
```



