---
title: "HGP analysis: fit model"
author: 
- name: Rick Farouni, 
  affiliation:
  - &cruk Department of Human Genetics, McGill University,  Montreal, Canada
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_notebook:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

# Preparations

```{r setup}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file(), fig.width=16)
options(scipen=999)
```


```{r}
library(tidyverse)
library(tictoc)
options(future.globals.maxSize= 10000000000)
plan(multicore)
```



```{r}
bas_filepath <- "./data/metadata/average_quality_dt.txt"
bas_dt <- read_tsv(bas_filepath)
avg_qual_mean <- bas_dt$avg_qual_mean
```

```{r}
LF <- readRDS("./data/preprocessed/lf.rds")
```


```{r}
bas_dt <- bind_cols(bas_dt,
                    tibble(lf1=LF[,1], lf2=LF[,2],lf3=LF[,3]))
```

```{r}
ggplot(bas_dt,
       aes(lf2, lf3, color=Population)) +
  geom_point(size=0.6, alpha=.6) +
  theme_bw()
```












```{r}
ggplot(bas_dt,
       aes(lf1, lf3, color=Population)) +
  geom_point(size=0.6, alpha=.6) +
  theme_bw()
```


```{r}
ggplot(bas_dt,
       aes(lf1, lf2, color=Population)) +
  geom_point(size=0.6, alpha=.6) +
  theme_bw()
```

