---
title: "LFA analysis"
author: 
- name: Rick Farouni + Luke
  affiliation:
  - &cruk Department of Human Genetics, McGill University,  Montreal, Canada
date: '`r format(Sys.Date(), "%Y-%B-%d")`'
output:
  html_notebook:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float: 
      collapsed: false
      smooth_scroll: false
---

```{r}
library(Matrix)
library(irlba)
library(threejs)
library(tidyverse)
library(lfa)
library(furrr)
library(broom)
options(future.globals.maxSize= 10000000000)
future::plan(multicore)
```

# Logistic factor analysis

```{r}
GenoPath='/Users/luke/genomes/genomes/Genotype/'

to_datalist <- function(i, data_genotype, data_iaf){
  
    data <- tibble(genotype=data_genotype[i,],
               iaf=data_iaf[i,])
               
     return(data)       
}

get_data <- function(){
  
  p <- pipe(paste("cat ",GenoPath,"1KG_DownSample_noDup_header.chip.omni.vcf |
          sed /^#/d  |
          cut  -f '10-' |
          ./a.out | 
          cut -f '1-2'",sep=''))
  x <- read.table(p,
                colClasses=c("integer","integer"), 
                fill=TRUE,
                row.names=NULL)

  
  data <- sparseMatrix(i=x[,2], j=x[,1], x=1L)
  
  data.csc <- new("matrix.csc", ra = data@x,
                           ja = data@i + 1L,
                           ia = data@p + 1L,
                           dimension = data@Dim)
  
  data.csr <- as.matrix.csr(data.csc)
  
  return(data.csr)
  
}
  
get_af_data <- function(data, d=4){
  
  # compute the first d factors including the intercept
  LF <- lfa(data, d)
  # compute the individual-specific allele frequencies
  data_iaf <- af(data, LF)
  loci <- c(1:dim(data)[1])
  names(loci) <- loci
  
  data_list <- future_map(loci, 
                 to_datalist,
                 data_genotype=data,
                 data_iaf=data_iaf) 
  
  data_list <- 
  enframe(data_list,
          name = "locus", 
          value = "dataset")
  
  return(data_list)
  
}

```

```{r}

data <- get_data()
data <- t(as.matrix(data))

```

```{r}
data_list <- get_af_data(data) 

rm(data)

save(data_list, '/Users/luke/Documents/QualityPaper/rick/LFA_GenotypeData.RData')
```